In [ ]:
## **Machine Learning Zoomcamp**

### **1.8 Linear algebra refresher**

Plan:

    - vector operations
    - multiplication
        - vector-vector multiplication
        - matrix-vector multiplication
        - matrix-matrix multiplication
    - identity matrix
    - inverse

In [3]:
import numpy as np

### **vector operations**

In [23]:
u = np.array([2, 4, 5, 6])
u

array([2, 4, 5, 6])

In [11]:
2 * u

array([ 4,  8, 10, 12])

In [8]:
v = np.array([1, 0, 0, 2])
v

array([1, 0, 0, 2])

In [9]:
u + v

array([3, 4, 5, 8])

### **multiplication**

In [13]:
v.shape

(4,)

In [14]:
u.shape

(4,)

In [16]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]
    result = 0.0
    for i in range(n):
        result = result + u[i] * v[i]
    return result

In [17]:
vector_vector_multiplication(u, v)

np.float64(14.0)

In [12]:
u * v

array([ 2,  0,  0, 12])

In [18]:
u.dot(v)

np.int64(14)

In [30]:
U = np.array([
[2, 4, 5, 6],
[1, 2, 1, 2],
[3, 1, 2, 1]
     ])
U.shape

(3, 4)

In [35]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    return result
        

In [36]:
matrix_vector_multiplication(U, v)

array([14.,  5.,  5.])

In [38]:
U.dot(v)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [37]:
v = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0],
    
])