In [2]:
import numpy as np

In [3]:
np

<module 'numpy' from '/usr/local/python/3.12.1/lib/python3.12/site-packages/numpy/__init__.py'>

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
[1, 2, 3, 5, 7, 12]

[1, 2, 3, 5, 7, 12]

In [11]:
a = np.array([1, 2, 3, 5, 7, 12])

In [13]:
a[2] = 10

In [14]:
a

array([ 1,  2, 10,  5,  7, 12])

In [18]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [22]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multi-dimensional arrays

In [24]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [26]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [31]:
n[0][1] = 20

In [37]:
n[2] = [1, 1, 1]

In [44]:
n[:, 2] = [0, 1, 2] ##changing values in the second column

## Randomly generated arrays

In [50]:
np.random.seed(2)
100 * np.random.rand(5, 2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [49]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [51]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise operations

In [53]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [63]:
b = (10 + (a * 2))** 2/100

In [64]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

## Comparison operators

In [66]:
a

array([0, 1, 2, 3, 4])

In [67]:
a >= 2

array([False, False,  True,  True,  True])

In [71]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [72]:
a > b

array([False, False,  True,  True,  True])

In [73]:
a[a > b] # elements of a for which a > b

array([2, 3, 4])

## summarizing operations

In [74]:
a

array([0, 1, 2, 3, 4])

In [75]:
a.min()

np.int64(0)

In [76]:
a.max()

np.int64(4)

In [79]:
a.sum()

np.int64(10)

In [80]:
a.std()

np.float64(1.4142135623730951)

In [81]:
a.mean()

np.float64(2.0)

In [82]:
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

In [83]:
n.sum()

np.int64(35)

In [85]:
n.min()

np.int64(0)